channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=25.0
- pip:
  - mlflow==2.21.2
  - astunparse==1.6.3
  - attrs==25.1.0
  - cloudpickle==3.1.1
  - colorama==0.4.6
  - matplotlib==3.10.0
  - numpy==2.2.4
  - nvidia-ml-py==12.570.86
  - optree==0.14.1
  - pandas==2.2.3
  - pydot==3.0.4
  - pytorch-lightning==2.5.1
  - rich==13.9.4
  - scipy==1.15.2
  - torch==2.6.0
  - torchvision==0.21.0
name: mlflow-env
